# version: "3.9"  # Composeファイルのバージョン (Docker Engineのバージョンに合わせて調整)

services:
  gen_3dv:  # サービス名 (任意)
    build:
      context: .  # Dockerfileがあるディレクトリ
      dockerfile: Dockerfile  # Dockerfileのファイル名 (デフォルトはDockerfile)
    container_name: gen_3dv-container
    image: gen_3dv:latest # ビルドするイメージ名とタグ (任意)
    tty: true
    network_mode: host  # ホストネットワークを使用
    shm_size: 8gb
    volumes:
      - .:/app  # ホストのカレントディレクトリをコンテナの/appにマウント
      # X-window
      - ~/.ssh:/root/.ssh
      - ~/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=:1 #VNCServer
      - LIBGL_ALWAYS_INDIRECT=0
    # host gpu を使えるようにする設定　https://docs.docker.jp/compose/gpu-support.html
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
